# Generated by Django 2.2 on 2020-08-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200830_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='attempt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='retake_status',
            field=models.BooleanField(default=True),
        ),
    ]
